### PR TITLE
Huge Refactor: Lazarus cross platform version using mORMot2 framework

### PR DESCRIPTION
**Pull request by AndreasLrx**
I refactored this project in Lazarus using the new mORMot2 cross platform Ldap client.

It may require some changes/fixes because I didn't fully have the project code in mind, but it's a start toward an Open Source and cross platform ldap interface.

Additional features (thanks to [mORMot2 ](https://github.com/synopse/mORMot2) framework):
- GSS-API / Kerberos authentication
- Improved SSL/TLS 

I leave it as a draft pull request to avoid it being merged by mistake since I cannot assure it doesn't break anything.

Nb: This was made in [Tranquil IT](https://www.tranquil.it/) as an help toward open source projects

### CODE REVIEW

**Comment by ibv** [comment]
Hi, good work :)
What version of mORMot2 is used? I have version [mORMot 2.0 stable](https://github.com/synopse/mORMot2/releases) and I have a problem 
when compiling in the LinLDAP unit, the ldap_get_values function. The error message is
LinLDAP.pas(1355,24) Error: identifier identifies no member "GetAllReadable"
o-008

**Comment by AndreasLrx** [comment]
I'm sorry it seems I forgot to push my last commit which added a submodule for mORMot version. I just pushed it.
And it is the master version of mORMot (or close to master)

**Comment by ibv** [comment]
Yes, compilation is possible.
Several manual steps are required to run/compile the program:
-  installation of static mormot obj module
-  for SSL, mormot.lib.openssl11 must be added to LinLDAP unit

In LDAP-Admin, there are SSL and TLS options in the connection properties, it will probably be good to combine them into one SSL/TLS option. Today, more TLS is used, when this option is turned on, the mormot library reports an error.
When using library synapse and TLS option, the connection is established using STARTTLS, mormot libraries use TLS even when SSL is selected, but this does not affect the correct function of the program.
I did all the tests on Linux, I haven't tested the Windows version yet. What I would be very interested in is the use of kerberos authentication on Linux, I haven't tested it yet.
Otherwise great work and moving to mormot framework will be a good thing.

**Comment by ibv** [comment]
Request accepted.

**Pull request merged**
